#!/bin/sh
set -e

# sets the current night map of our minecraft server as the wallpaper
# kinda cool

cd ~

LOCATION="$HOME/wallpaper-`date +%s`.png"
echo $LOCATION

curl townhall.acryps.com/wallpaper/pilegron/large > "$LOCATION"

echo "setting"
osascript -e "tell application \"System Events\" to set picture of every desktop to \"$LOCATION\""

echo "done"
